apiVersion: apps/v1
kind: Deployment
metadata:
  name: student05-deployment
  namespace: student05
spec:
  selector:
    matchLabels:
      app: student05
  template:
    metadata:
      labels:
        app: student05
    spec:
      containers:
      - name: student05
        image: registry.tanzu.dk/ops2devops/student05:v1
