apiVersion: apps/v1
kind: Deployment
metadata:
  name: student05-deployment
  namespace: student05
spec:
  selector:
    matchLabels:
      app: student05
  template:
    metadata:
      labels:
        app: student05
    spec:
      containers:
      - name: student05
        image: registry.tanzu.dk/ops2devops/student05:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student05
spec:
  type: NodePort
  selector:
    app: student05
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30015 # Remember to change to student number.

